Reduced Lagrange Multipliers: PoissonProblem< dim, spacedim > Class Template Reference
PoissonProblem< dim, spacedim > Class Template Reference
#include <laplacian.h>
Public Member Functions
PoissonProblem (const ProblemParameters< dim, spacedim > &par)
void make_grid ()
void setup_fe ()
void setup_dofs ()
void assemble_poisson_system ()
void assemble_coupling ()
void run ()
IndexSet assemble_coupling_sparsity (DynamicSparsityPattern &dsp) const
void solve ()
void refine_and_transfer ()
std::string output_solution () const
void output_results () const
void print_parameters () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Types
using VectorType = LA::MPI::Vector
using BlockVectorType = LA::MPI::BlockVector
Private Attributes
const ProblemParameters< dim, spacedim > & par
MPI_Comm mpi_communicator
ConditionalOStream pcout
TimerOutput computing_timer
parallel::distributed::Triangulation< spacedim > tria
std::unique_ptr< FiniteElement< spacedim > > fe
Inclusions< spacedim > inclusions
std::unique_ptr< Quadrature< spacedim > > quadrature
DoFHandler< spacedim > dh
std::vector< IndexSet > owned_dofs
std::vector< IndexSet > relevant_dofs
AffineConstraints< double > constraints
AffineConstraints< double > inclusion_constraints
LA::MPI::SparseMatrix coupling_matrix
LA::MPI::SparseMatrix inclusion_matrix
LA::MPI::SparseMatrix mass_matrix
MappingQ< spacedim > mapping
LA::MPI::SparseMatrix stiffness_matrix
BlockVectorType solution
BlockVectorType locally_relevant_solution
BlockVectorType system_rhs
std::vector< std::vector< BoundingBox< spacedim > > > global_bounding_boxes
unsigned int cycle = 0
Additional Inherited Members
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, int spacedim = dim>
class PoissonProblem< dim, spacedim >
Definition at line 192 of file laplacian.h.
Member Typedef Documentation
BlockVectorType
template<int dim, int spacedim = dim> using PoissonProblem< dim, spacedim >::BlockVectorType = LA::MPI::BlockVector private
Definition at line 272 of file laplacian.h.
VectorType
template<int dim, int spacedim = dim> using PoissonProblem< dim, spacedim >::VectorType = LA::MPI::Vector private
Definition at line 271 of file laplacian.h.
Constructor & Destructor Documentation
PoissonProblem()
template<int dim, int spacedim> PoissonProblem< dim, spacedim >::PoissonProblem (const ProblemParameters< dim, spacedim > & par)
Definition at line 47 of file laplacian.cc.
References computing_timer, dh, mapping, mpi_communicator, par, pcout, and tria.
Member Function Documentation
assemble_coupling()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::assemble_coupling ()
Definition at line 406 of file laplacian.cc.
References VectorOperation::add, computing_timer, constraints, coupling_matrix, dh, fe, inclusion_constraints, inclusion_matrix, inclusions, mass_matrix, pcout, FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_value(), stiffness_matrix, and system_rhs.
Referenced by run().
assemble_coupling_sparsity()
template<int dim, int spacedim> IndexSet PoissonProblem< dim, spacedim >::assemble_coupling_sparsity (DynamicSparsityPattern & dsp) const
Builds coupling sparsity, and returns locally relevant inclusion dofs.
Definition at line 359 of file laplacian.cc.
References IndexSet::add_indices(), computing_timer, constraints, dh, fe, inclusion_constraints, and inclusions.
Referenced by setup_dofs().
assemble_poisson_system()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::assemble_poisson_system ()
Definition at line 305 of file laplacian.cc.
References VectorOperation::add, constraints, coupling_matrix, dh, fe, FEValues< int dim, int spacedim >::get_quadrature_points(), FEValues< int dim, int spacedim >::JxW(), par, quadrature, FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_value(), stiffness_matrix, and system_rhs.
Referenced by run().
make_grid()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::make_grid ()
Definition at line 122 of file laplacian.cc.
References GridGenerator::generate_from_name_and_arguments(), par, pcout, read_grid_and_cad_files(), and tria.
Referenced by run().
output_results()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::output_results () const
Definition at line 909 of file laplacian.cc.
References cycle, inclusions, output_solution(), par, and DataOutBase::write_pvd_record().
Referenced by run().
output_solution()
template<int dim, int spacedim> std::string PoissonProblem< dim, spacedim >::output_solution () const
Definition at line 871 of file laplacian.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), computing_timer, cycle, dh, locally_relevant_solution, mpi_communicator, par, Vector< typename Number >::size(), tria, and DataOut< int dim, int spacedim >::write_vtu_in_parallel().
Referenced by output_results().
print_parameters()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::print_parameters () const
Definition at line 936 of file laplacian.cc.
References Utilities::dim_string(), par, pcout, and ParameterHandler::Short.
Referenced by run().
refine_and_transfer()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::refine_and_transfer ()
Definition at line 826 of file laplacian.cc.
References computing_timer, constraints, dh, KellyErrorEstimator< int dim, int spacedim >::estimate(), inclusions, SolutionTransfer< int dim, typename VectorType, int spacedim >::interpolate(), locally_relevant_solution, par, SolutionTransfer< int dim, typename VectorType, int spacedim >::prepare_for_coarsening_and_refinement(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), setup_dofs(), solution, and tria.
Referenced by run().
run()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::run ()
Definition at line 953 of file laplacian.cc.
References assemble_coupling(), assemble_poisson_system(), constraints, cycle, dh, fe, inclusions, locally_relevant_solution, make_grid(), mapping, output_results(), par, pcout, print_parameters(), refine_and_transfer(), setup_dofs(), setup_fe(), solve(), and tria.
setup_dofs()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::setup_dofs ()
Definition at line 153 of file laplacian.cc.
References DynamicSparsityPattern::add(), assemble_coupling_sparsity(), AffineConstraints< typename number >::close(), computing_timer, AffineConstraints< typename number >::constrain_dof_to_zero(), constraints, coupling_matrix, Utilities::MPI::create_evenly_distributed_partitioning(), dh, SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), DoFTools::extract_locally_relevant_level_dofs(), fe, inclusion_constraints, inclusion_matrix, inclusions, VectorTools::interpolate_boundary_values(), locally_relevant_solution, DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), mapping, MatrixFree::AdditionalData::mapping_update_flags, mass_matrix, MatrixFree::AdditionalData::mg_level, mpi_communicator, MatrixFree::AdditionalData::none, owned_dofs, par, pcout, relevant_dofs, solution, stiffness_matrix, system_rhs, MatrixFree::AdditionalData::tasks_parallel_scheme, and tria.
Referenced by refine_and_transfer(), and run().
setup_fe()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::setup_fe ()
Definition at line 143 of file laplacian.cc.
References computing_timer, fe, par, and quadrature.
Referenced by run().
solve()
template<int dim, int spacedim> void PoissonProblem< dim, spacedim >::solve ()
Augmented the (1,1) block
augmented
Definition at line 573 of file laplacian.cc.
References MGTransferMatrixFree< int dim, typename Number, typename MemorySpace >::build(), computing_timer, SolverCG< typename VectorType >::connect_condition_number_slot(), constraints, coupling_matrix, dh, inclusion_constraints, inclusion_matrix, inclusions, MGCoarseGridApplySmoother< typename VectorType >::initialize(), TrilinosWrappers::PreconditionILU::initialize(), numbers::invalid_unsigned_int, locally_relevant_solution, mass_matrix, mpi_communicator, output_double_number(), owned_dofs, par, pcout, relevant_dofs, MGLevelObject< class Object >::resize(), solution, SolverCG< typename VectorType >::solve(), SolverFGMRES< typename VectorType >::solve(), stiffness_matrix, system_rhs, and tria.
Referenced by run().
Member Data Documentation
computing_timer
template<int dim, int spacedim = dim> TimerOutput PoissonProblem< dim, spacedim >::computing_timer mutable private
Definition at line 239 of file laplacian.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), output_solution(), PoissonProblem(), refine_and_transfer(), setup_dofs(), setup_fe(), and solve().
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PoissonProblem< dim, spacedim >::constraints private
Definition at line 249 of file laplacian.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_poisson_system(), refine_and_transfer(), run(), setup_dofs(), and solve().
coupling_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix PoissonProblem< dim, spacedim >::coupling_matrix private
Definition at line 252 of file laplacian.h.
Referenced by assemble_coupling(), assemble_poisson_system(), setup_dofs(), and solve().
cycle
template<int dim, int spacedim = dim> unsigned int PoissonProblem< dim, spacedim >::cycle = 0 private
Definition at line 279 of file laplacian.h.
Referenced by output_results(), output_solution(), and run().
dh
template<int dim, int spacedim = dim> DoFHandler<spacedim> PoissonProblem< dim, spacedim >::dh private
Definition at line 245 of file laplacian.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_poisson_system(), output_solution(), PoissonProblem(), refine_and_transfer(), run(), setup_dofs(), and solve().
fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<spacedim> > PoissonProblem< dim, spacedim >::fe private
Definition at line 241 of file laplacian.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_poisson_system(), run(), setup_dofs(), and setup_fe().
global_bounding_boxes
template<int dim, int spacedim = dim> std::vector<std::vector<BoundingBox<spacedim> > > PoissonProblem< dim, spacedim >::global_bounding_boxes private
Definition at line 278 of file laplacian.h.
inclusion_constraints
template<int dim, int spacedim = dim> AffineConstraints<double> PoissonProblem< dim, spacedim >::inclusion_constraints private
Definition at line 250 of file laplacian.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), setup_dofs(), and solve().
inclusion_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix PoissonProblem< dim, spacedim >::inclusion_matrix private
Definition at line 253 of file laplacian.h.
Referenced by assemble_coupling(), setup_dofs(), and solve().
inclusions
template<int dim, int spacedim = dim> Inclusions<spacedim> PoissonProblem< dim, spacedim >::inclusions private
Definition at line 242 of file laplacian.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), output_results(), refine_and_transfer(), run(), setup_dofs(), and solve().
locally_relevant_solution
template<int dim, int spacedim = dim> BlockVectorType PoissonProblem< dim, spacedim >::locally_relevant_solution private
Definition at line 276 of file laplacian.h.
Referenced by output_solution(), refine_and_transfer(), run(), setup_dofs(), and solve().
mapping
template<int dim, int spacedim = dim> MappingQ<spacedim> PoissonProblem< dim, spacedim >::mapping private
Definition at line 255 of file laplacian.h.
Referenced by PoissonProblem(), run(), and setup_dofs().
mass_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix PoissonProblem< dim, spacedim >::mass_matrix private
Definition at line 254 of file laplacian.h.
Referenced by assemble_coupling(), setup_dofs(), and solve().
mpi_communicator
template<int dim, int spacedim = dim> MPI_Comm PoissonProblem< dim, spacedim >::mpi_communicator private
Definition at line 237 of file laplacian.h.
Referenced by output_solution(), PoissonProblem(), setup_dofs(), and solve().
owned_dofs
template<int dim, int spacedim = dim> std::vector<IndexSet> PoissonProblem< dim, spacedim >::owned_dofs private
Definition at line 246 of file laplacian.h.
Referenced by setup_dofs(), and solve().
par
template<int dim, int spacedim = dim> const ProblemParameters<dim, spacedim>& PoissonProblem< dim, spacedim >::par private
Definition at line 236 of file laplacian.h.
Referenced by assemble_poisson_system(), make_grid(), output_results(), output_solution(), PoissonProblem(), print_parameters(), refine_and_transfer(), run(), setup_dofs(), setup_fe(), and solve().
pcout
template<int dim, int spacedim = dim> ConditionalOStream PoissonProblem< dim, spacedim >::pcout private
Definition at line 238 of file laplacian.h.
Referenced by assemble_coupling(), make_grid(), PoissonProblem(), print_parameters(), run(), setup_dofs(), and solve().
quadrature
template<int dim, int spacedim = dim> std::unique_ptr<Quadrature<spacedim> > PoissonProblem< dim, spacedim >::quadrature private
Definition at line 243 of file laplacian.h.
Referenced by assemble_poisson_system(), and setup_fe().
relevant_dofs
template<int dim, int spacedim = dim> std::vector<IndexSet> PoissonProblem< dim, spacedim >::relevant_dofs private
Definition at line 247 of file laplacian.h.
Referenced by setup_dofs(), and solve().
solution
template<int dim, int spacedim = dim> BlockVectorType PoissonProblem< dim, spacedim >::solution private
Definition at line 275 of file laplacian.h.
Referenced by refine_and_transfer(), setup_dofs(), and solve().
stiffness_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix PoissonProblem< dim, spacedim >::stiffness_matrix private
Definition at line 270 of file laplacian.h.
Referenced by assemble_coupling(), assemble_poisson_system(), setup_dofs(), and solve().
system_rhs
template<int dim, int spacedim = dim> BlockVectorType PoissonProblem< dim, spacedim >::system_rhs private
Definition at line 277 of file laplacian.h.
Referenced by assemble_coupling(), assemble_poisson_system(), setup_dofs(), and solve().
tria
template<int dim, int spacedim = dim> parallel::distributed::Triangulation<spacedim> PoissonProblem< dim, spacedim >::tria private
Definition at line 240 of file laplacian.h.
Referenced by make_grid(), output_solution(), PoissonProblem(), refine_and_transfer(), run(), setup_dofs(), and solve().
The documentation for this class was generated from the following files:
/github/workspace/include/laplacian.h
/github/workspace/source/laplacian.cc