Reduced Lagrange Multipliers: ElasticityProblem< dim, spacedim > Class Template Reference
ElasticityProblem< dim, spacedim > Class Template Reference
#include <elasticity.h>
Public Member Functions
ElasticityProblem (const ElasticityProblemParameters< dim, spacedim > &par)
void make_grid ()
void setup_fe ()
void setup_dofs ()
void assemble_elasticity_system ()
void assemble_forcing_terms ()
void compute_system_rhs ()
void assemble_coupling ()
void run ()
set up, assemble and run the problem
void run_static ()
void run_quasistatic ()
void run_newmark ()
IndexSet assemble_coupling_sparsity (DynamicSparsityPattern &dsp)
void solve ()
void solve_static ()
void solve_quasistatic ()
void solve_newmark ()
void refine_and_transfer ()
void refine_and_transfer_around_inclusions ()
void execute_actual_refine_and_transfer ()
std::string output_solution () const
void output_results () const
void print_parameters () const
void compute_internal_and_boundary_stress (bool) const
compute stresses on boundaries (2D and 3D) and internal (2D) this function makes use of boundary id, so make sure that the ifd starts from 0 and are sequential when importing a mesh, this is automatically taken care of for meshes generated with GridTools output is a txt file containing stresses at each cycle/time
void output_lambda () const
std::string output_stresses () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Attributes
const ElasticityProblemParameters< dim, spacedim > & par
MPI_Comm mpi_communicator
ConditionalOStream pcout
TimerOutput computing_timer
parallel::distributed::Triangulation< spacedim > tria
std::unique_ptr< FiniteElement< spacedim > > fe
Inclusions< spacedim > inclusions
std::unique_ptr< Quadrature< spacedim > > quadrature
std::unique_ptr< Quadrature< spacedim - 1 > > face_quadrature_formula
DoFHandler< spacedim > dh
std::vector< IndexSet > owned_dofs
std::vector< IndexSet > relevant_dofs
AffineConstraints< double > constraints
AffineConstraints< double > inclusion_constraints
AffineConstraints< double > mean_value_constraints
LA::MPI::SparseMatrix stiffness_matrix
LA::MPI::SparseMatrix newmark_matrix
LA::MPI::SparseMatrix mass_matrix
LA::MPI::SparseMatrix coupling_matrix
LA::MPI::SparseMatrix damping_matrix
LA::MPI::PreconditionAMG prec_A
LA::MPI::PreconditionAMG prec_newmark
LA::MPI::PreconditionAMG prec_C
LA::MPI::PreconditionAMG prec_M
LA::MPI::SparseMatrix inclusion_matrix
LA::MPI::BlockVector solution
LA::MPI::BlockVector velocity
LA::MPI::BlockVector acceleration
LA::MPI::BlockVector predictor
LA::MPI::BlockVector corrector
LA::MPI::BlockVector locally_relevant_solution
LA::MPI::BlockVector force_rhs
LA::MPI::BlockVector bc_rhs
LA::MPI::BlockVector neumann_bc_rhs
LA::MPI::BlockVector system_rhs
std::vector< std::vector< BoundingBox< spacedim > > > global_bounding_boxes
unsigned int cycle = 0
unsigned int time_step = 0
FEValuesExtractors::Vector displacement
std::map< types::boundary_id, Tensor< 1, spacedim > > forces
std::map< types::boundary_id, Tensor< 1, spacedim > > average_displacements
std::map< types::boundary_id, Tensor< 1, spacedim > > average_normals
std::map< types::boundary_id, double > areas
TrilinosWrappers::MPI::Vector sigma_n
double current_time = 0.0
Additional Inherited Members
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, int spacedim = dim>
class ElasticityProblem< dim, spacedim >
Finite element model for (optionally) time-dependent elasticity, coupled to immersed 1D/0D inclusions via reduced Lagrange multipliers.
This class assembles a small set of global sparse matrices and then solves either:
a pure displacement problem (no inclusions), or
a saddle-point problem for displacement and Lagrange multipliers, or
a displacement problem driven by inclusion "pressure" data (when ElasticityProblemParameters::pressure_coupling is enabled).
The intent of this documentation is to state exactly which continuous and discrete equations correspond to the current implementation in source/elasticity.cc (primarily assemble_elasticity_system(), assemble_coupling(), and solve()), and to list the constants and options that select between different model variants.
Note
The bulk constitutive model is selected via ElasticityProblemParameters::elasticity_model (inferred from material parameters). Rayleigh damping is determined by the per-material parameters MaterialProperties::{rayleigh_alpha,rayleigh_beta}.
Template Parameters
dim Topological dimension of the mesh (typically equal to spacedim).
spacedim Embedding space dimension. The displacement has spacedim components.
Unknowns, discrete spaces, and blocks
Let \(\Omega \subset \mathbb{R}^{spacedim}\) be the computational domain.
Primary unknown: displacement \(u:\Omega\to\mathbb{R}^{spacedim}\).
Optional secondary unknown: reduced Lagrange multipliers \(\lambda \in \mathbb{R}^{N_\lambda}\) attached to immersed inclusions (Inclusions<spacedim>).
In the code, the global solution is stored as a 2-block vector:
solution.block(0) \(\equiv u_h\),
solution.block(1) \(\equiv \lambda_h\) (may be size 0 if no inclusions).
The displacement is discretized with a continuous \(Q_p\) vector element: FESystem<spacedim>(FE_Q<spacedim>(fe_degree), spacedim).
Assembled matrices and right-hand sides
The following sparse matrices are assembled explicitly:
stiffness_matrix \(\equiv A\)
mass_matrix \(\equiv C\)
damping_matrix \(\equiv D\)
coupling_matrix \(\equiv B^T\) (maps \(\lambda\) to displacement dofs)
inclusion_matrix \(\equiv M\) (multiplier mass / scaling matrix)
Right-hand side blocks are:
system_rhs.block(0) \(\equiv f\) (volumetric + boundary loads and penalty terms),
system_rhs.block(1) \(\equiv g\) (inclusion data projected onto the multiplier basis),
system_rhs_f.block(0) \(\equiv f_f\) (computed in solve() as \(f_f=B^T\lambda\) in some branches; it is not assembled in assemble_elasticity_system()).
Constants and where they come from
Material constants are taken per-cell from MaterialProperties (see include/material_properties.h):
\(\mu\) = MaterialProperties::Lame_mu
\(\lambda\) = MaterialProperties::Lame_lambda
\(\rho\) = MaterialProperties::rho
\(\eta\) = MaterialProperties::neta (KelvinVoigt viscosity)
\(\alpha\) = MaterialProperties::rayleigh_alpha
\(\beta\) = MaterialProperties::rayleigh_beta
Model/solver constants are taken from ElasticityProblemParameters (see include/elasticity_problem_parameters.h):
penalty coefficient \(\gamma_p\) = ElasticityProblemParameters::penalty_term
"wave" amplitude \(a_w\) = ElasticityProblemParameters::wave_ampltiude
time step \(\Delta t\) = ElasticityProblemParameters::dt
Newmark parameters \(\beta_N\) and \(\gamma_N\) = ElasticityProblemParameters::beta and ElasticityProblemParameters::gamma
A single length scale \(h\) used in the penalty term is computed as GridTools::minimal_cell_diameter(tria) in assemble_elasticity_system().
Bulk constitutive forms (what goes into A, C, D)
Define the symmetric gradient \(\varepsilon(u)=\frac12(\nabla u+\nabla u^T)\) and divergence \(\nabla\cdot u\).
Let \(\{\varphi_i\}\) be the displacement FE basis functions (vector-valued), and let \(\langle \cdot, \cdot \rangle\) denote the Euclidean inner product on vectors/tensors. The entries assembled in assemble_elasticity_system() are:
Mass matrix (always assembled):
\[ C_{ij} = \int_\Omega \rho\, \varphi_i \cdot \varphi_j\,dx. \]
Stiffness matrix contributions (assembled depending on flags):
If ElasticityProblemParameters::elasticity_model == ElasticityModel::LinearElasticity:
\[ A_{ij} \mathrel{+}= \int_\Omega \Big(2\mu\,\varepsilon(\varphi_i):\varepsilon(\varphi_j) + \lambda\,(\nabla\cdot \varphi_i)(\nabla\cdot \varphi_j)\Big)\,dx. \]
If ElasticityProblemParameters::elasticity_model == ElasticityModel::KelvinVoigt (note: the current implementation uses only the \(\mu\) term for stiffness, without a \(\lambda\) contribution):
\[ A_{ij} \mathrel{+}= \int_\Omega \mu\,\varepsilon(\varphi_i):\varepsilon(\varphi_j)\,dx. \]
Damping matrix contributions:
If ElasticityProblemParameters::elasticity_model == ElasticityModel::KelvinVoigt:
\[ D_{ij} \mathrel{+}= \int_\Omega \eta\,\varepsilon(\varphi_i):\varepsilon(\varphi_j)\,dx. \]
If any material has nonzero Rayleigh parameters, the code builds (intended) Rayleigh damping of the form
\[ D \approx \beta\,A + \alpha\,C, \]
with \(\alpha=\) MaterialProperties::rayleigh_alpha and \(\beta=\) MaterialProperties::rayleigh_beta.
Body force right-hand side (always assembled):
\[ f_i \mathrel{+}= \int_\Omega \varphi_i \cdot f_{\text{rhs}}(x)\,dx, \]
where f_rhs comes from ElasticityProblemParameters::rhs.
Boundary conditions (as implemented)
Strong Dirichlet boundary conditions:
On boundary ids in ElasticityProblemParameters::dirichlet_ids, the code applies \(u = u_D\) strongly via VectorTools::interpolate_boundary_values(..., par.bc, constraints).
Normal-flux constraints:
On boundary ids in ElasticityProblemParameters::normal_flux_ids, the code adds constraints via VectorTools::compute_nonzero_normal_flux_constraints(...) using ElasticityProblemParameters::Neumann_bc. (This constrains the net normal flux; see the deal.II function documentation for the exact constraint meaning.)
Neumann boundary ids:
On boundary ids in ElasticityProblemParameters::neumann_ids, the code adds a scalar traction-like load computed as \(t_n(x)=\frac{1}{spacedim}\,(\texttt{Neumann\_bc}(x)\cdot n(x))\) and assembled as
\[ f_i \mathrel{+}= -\int_{\Gamma_N} t_n\, \varphi_i\,ds. \]
Weak Dirichlet ids (penalty term):
For cells that have at least one boundary face with id in ElasticityProblemParameters::weak_dirichlet_ids, the code adds a penalty term using \(h = \) GridTools::minimal_cell_diameter(tria):
\[ A_{ij} \mathrel{+}= \frac{\gamma_p}{h}\int_{\Omega_{\text{marked}}} \varphi_i\cdot\varphi_j\,dx,\qquad f_i \mathrel{+}= \frac{\gamma_p}{h}\,a_w\int_{\Omega_{\text{marked}}}\varphi_i\,dx. \]
with \(\gamma_p=\) penalty_term and \(a_w=\) wave_ampltiude.
Inclusion coupling (B, M, g) and equation
types
The immersed inclusions define a reduced multiplier space with basis values (Fourier/harmonic modes) evaluated at quadrature points on each inclusion. In the code, assemble_coupling() builds:
Coupling matrix \(B^T\) (coupling_matrix, size \(N_u\times N_\lambda\)),
Inclusion matrix \(M\) (inclusion_matrix, size \(N_\lambda\times N_\lambda\), assembled diagonally),
Multiplier right-hand side \(g\) (system_rhs.block(1)).
Conceptually, the saddle-point branch (pressure_coupling == false) solves the discrete constrained system
\[\begin{bmatrix} A & B^T \\ B & 0 \end{bmatrix} \begin{bmatrix} u \\ \lambda \end{bmatrix} = \begin{bmatrix} f \\ g \end{bmatrix}. \]
The pressure_coupling == true branch does not solve the saddle-point problem. Instead it computes \(\lambda \approx M^{-1}g\) and then forms an additional load \(f_f = B^T\lambda\) (stored in system_rhs_f.block(0)).
Multiplier right-hand side \(g\) (as assembled in assemble_coupling()) is a normalized quadrature projection of the inclusion boundary data onto the selected Fourier coefficients. In particular, for each inclusion and each selected mode index \(j\), the code adds terms of the form
\[ g_j \mathrel{+}= \frac{1}{|\Gamma|}\sum_q \psi_j(q)\,d_j(q)\,ds_q, \]
with \(|\Gamma|=\) section_measure, basis value \(\psi_j(q)=\) inclusion_fe_values[j], and \(d_j(q)\) taken either from Inclusions::inclusions_rhs or from Inclusions::inclusions_data (see source/elasticity.cc, assemble_coupling()).
Note
In the stationary case (initial_time == final_time) with pressure_coupling == true, the current implementation computes \(f_f=B^T\lambda\) but then solves \(A u = f\) (i.e., \(f_f\) is not used in the stationary solve path).
Time integration (Newmark predictor/corrector)
If ElasticityProblemParameters::initial_time != final_time, the solver uses Newmark time integration for the (semi-discrete) second-order system
\[ C\,\ddot u + D\,\dot u + A\,u = \big(f + f_f\big)\,\sin(t), \]
where \(f_f=B^T\lambda\) is present only in the pressure_coupling == true branch (as implemented in solve()).
Given \(u^n, v^n=\dot u^n, a^n=\ddot u^n\), the code computes: Predictor:
\[ u^{pred} = u^n + \Delta t\,v^n + \frac{\Delta t^2}{2}(1-2\beta_N)a^n,\qquad v^{pred} = v^n + \Delta t(1-\gamma_N)a^n. \]
Effective (acceleration) solve:
Linear elasticity:
\[ \big(C + \beta_N\Delta t^2 A\big)a^{n+1} = (f+f_f)\sin(t^n) - A\,u^{pred}. \]
With damping (Rayleigh and/or KelvinVoigt):
\[ \big(C + \beta_N\Delta t^2 A + \gamma_N\Delta t\,D\big)a^{n+1} = (f+f_f)\sin(t^n) - D\,v^{pred} - A\,u^{pred}. \]
Corrector:
\[ u^{n+1} = u^{pred} + \beta_N\Delta t^2 a^{n+1},\qquad v^{n+1} = v^{pred} + \gamma_N\Delta t\, a^{n+1}. \]
Predictor/corrector matrices
For matrix-based solvers/preconditioners that work on assembled matrices, the key "effective" (acceleration) matrix used in the Newmark solve is:
\(A_n = C + \beta_N\Delta t^2 A\) (undamped)
\(A_n = C + \beta_N\Delta t^2 A + \gamma_N\Delta t\,D\) (damped)
In the current implementation these combinations are built as LinearOperator sums in solve() (not as explicit sparse matrices).
Definition at line 419 of file elasticity.h.
Constructor & Destructor Documentation
ElasticityProblem()
template<int dim, int spacedim> ElasticityProblem< dim, spacedim >::ElasticityProblem (const ElasticityProblemParameters< dim, spacedim > & par)
Definition at line 79 of file elasticity.cc.
References computing_timer, dh, displacement, inclusions, mpi_communicator, par, pcout, and tria.
Member Function Documentation
assemble_coupling()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::assemble_coupling ()
Definition at line 857 of file elasticity.cc.
References VectorOperation::add, computing_timer, constraints, coupling_matrix, dh, fe, force_rhs, inclusion_constraints, inclusion_matrix, inclusions, par, prec_M, FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_value(), and system_rhs.
Referenced by compute_system_rhs(), run_newmark(), run_quasistatic(), and run_static().
assemble_coupling_sparsity()
template<int dim, int spacedim> IndexSet ElasticityProblem< dim, spacedim >::assemble_coupling_sparsity (DynamicSparsityPattern & dsp)
Builds coupling sparsity, and returns locally relevant inclusion dofs.
Definition at line 811 of file elasticity.cc.
References IndexSet::add_indices(), computing_timer, constraints, dh, fe, inclusion_constraints, and inclusions.
Referenced by setup_dofs().
assemble_elasticity_system()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::assemble_elasticity_system ()
Definition at line 329 of file elasticity.cc.
References FullMatrix< typename number >::add(), Vector< typename Number >::add(), VectorOperation::add, computing_timer, constraints, coupling_matrix, current_time, damping_matrix, dh, displacement, Dynamic, FullMatrix< typename number >::equ(), DoFTools::extract_locally_relevant_dofs(), DoFTools::extract_rigid_body_modes(), face_quadrature_formula, fe, FEValues< int dim, int spacedim >::get_quadrature_points(), VectorTools::interpolate(), FEFaceValues< int dim, int spacedim >::JxW(), FEValues< int dim, int spacedim >::JxW(), mass_matrix, mpi_communicator, FEFaceValues< int dim, int spacedim >::n_quadrature_points, newmark_matrix, FEFaceValues< int dim, int spacedim >::normal_vector(), par, prec_A, prec_C, prec_newmark, quadrature, FEFaceValues< int dim, int spacedim >::quadrature_point(), FEFaceValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::reinit(), UtilitiesAL::set_null_space(), FEFaceValues< int dim, int spacedim >::shape_value(), FEValues< int dim, int spacedim >::shape_value(), Static, stiffness_matrix, and system_rhs.
Referenced by run_newmark(), run_quasistatic(), and run_static().
assemble_forcing_terms()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::assemble_forcing_terms ()
Definition at line 653 of file elasticity.cc.
References VectorOperation::add, bc_rhs, computing_timer, constraints, current_time, dh, displacement, face_quadrature_formula, fe, force_rhs, FEValues< int dim, int spacedim >::get_quadrature_points(), FEFaceValues< int dim, int spacedim >::JxW(), FEValues< int dim, int spacedim >::JxW(), FEFaceValues< int dim, int spacedim >::n_quadrature_points, neumann_bc_rhs, FEFaceValues< int dim, int spacedim >::normal_vector(), par, quadrature, FEFaceValues< int dim, int spacedim >::quadrature_point(), FEFaceValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::reinit(), FEFaceValues< int dim, int spacedim >::shape_value(), FEValues< int dim, int spacedim >::shape_value(), and system_rhs.
Referenced by compute_system_rhs(), run_newmark(), and run_quasistatic().
compute_internal_and_boundary_stress()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::compute_internal_and_boundary_stress (bool openfilefirsttime) const
compute stresses on boundaries (2D and 3D) and internal (2D) this function makes use of boundary id, so make sure that the ifd starts from 0 and are sequential when importing a mesh, this is automatically taken care of for meshes generated with GridTools output is a txt file containing stresses at each cycle/time
Definition at line 1661 of file elasticity.cc.
References computing_timer, cycle, dh, displacement, face_quadrature_formula, fe, FEFaceValues< int dim, int spacedim >::get_function_gradients(), FEFaceValues< int dim, int spacedim >::get_function_values(), FEFaceValues< int dim, int spacedim >::JxW(), locally_relevant_solution, mpi_communicator, FEFaceValues< int dim, int spacedim >::n_quadrature_points, FEFaceValues< int dim, int spacedim >::normal_vector(), par, FEFaceValues< int dim, int spacedim >::reinit(), Static, Utilities::MPI::sum(), Utilities::MPI::this_mpi_process(), time_step, and tria.
Referenced by run_newmark(), run_quasistatic(), and run_static().
compute_system_rhs()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::compute_system_rhs ()
Definition at line 2145 of file elasticity.cc.
References std::abs(), assemble_coupling(), assemble_forcing_terms(), bc_rhs, current_time, force_rhs, inclusions, neumann_bc_rhs, par, pcout, numbers::PI, std::sin(), and system_rhs.
Referenced by run_newmark(), and run_quasistatic().
execute_actual_refine_and_transfer()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::execute_actual_refine_and_transfer ()
Definition at line 1407 of file elasticity.cc.
References constraints, dh, inclusions, SolutionTransfer< int dim, typename VectorType, int spacedim >::interpolate(), locally_relevant_solution, SolutionTransfer< int dim, typename VectorType, int spacedim >::prepare_for_coarsening_and_refinement(), setup_dofs(), solution, and tria.
Referenced by refine_and_transfer().
make_grid()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::make_grid ()
Definition at line 101 of file elasticity.cc.
References GridIn< int dim, int spacedim >::attach_triangulation(), GridGenerator::cheese(), GridGenerator::generate_from_name_and_arguments(), GridGenerator::hyper_ball(), par, pcout, read_grid_and_cad_files(), GridIn< int dim, int spacedim >::read_msh(), and tria.
Referenced by run_newmark(), run_quasistatic(), and run_static().
output_lambda()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::output_lambda () const
Definition at line 1860 of file elasticity.cc.
References inclusions, locally_relevant_solution, and par.
Referenced by run_static().
output_results()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::output_results () const
Definition at line 1544 of file elasticity.cc.
References computing_timer, current_time, cycle, inclusions, output_solution(), par, Static, time_step, and DataOutBase::write_pvd_record().
Referenced by run_newmark(), run_quasistatic(), and run_static().
output_solution()
template<int dim, int spacedim> std::string ElasticityProblem< dim, spacedim >::output_solution () const
Definition at line 1430 of file elasticity.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), DataComponentInterpretation::component_is_part_of_vector, constraints, current_time, cycle, dh, VectorTools::interpolate(), locally_relevant_solution, mpi_communicator, par, Vector< typename Number >::size(), solution, Static, time_step, tria, DataOut< int dim, int spacedim >::type_dof_data, and DataOut< int dim, int spacedim >::write_vtu_in_parallel().
Referenced by output_results().
output_stresses()
template<int dim, int spacedim = dim> std::string ElasticityProblem< dim, spacedim >::output_stresses () const
print_parameters()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::print_parameters () const
Definition at line 1626 of file elasticity.cc.
References Utilities::dim_string(), ParameterHandler::KeepOnlyChanged, par, pcout, ParameterHandler::PRM, and ParameterHandler::Short.
Referenced by run_newmark(), run_quasistatic(), and run_static().
refine_and_transfer()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::refine_and_transfer ()
Definition at line 1375 of file elasticity.cc.
References computing_timer, dh, KellyErrorEstimator< int dim, int spacedim >::estimate(), execute_actual_refine_and_transfer(), locally_relevant_solution, par, parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), and tria.
Referenced by run_newmark(), run_quasistatic(), and run_static().
refine_and_transfer_around_inclusions()
template<int dim, int spacedim = dim> void ElasticityProblem< dim, spacedim >::refine_and_transfer_around_inclusions ()
run()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::run ()
set up, assemble and run the problem
Definition at line 1910 of file elasticity.cc.
References Dynamic, par, QuasiStatic, run_newmark(), run_quasistatic(), run_static(), and Static.
run_newmark()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::run_newmark ()
Definition at line 2034 of file elasticity.cc.
References acceleration, assemble_coupling(), assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), compute_system_rhs(), computing_timer, constraints, coupling_matrix, current_time, cycle, damping_matrix, dh, Dynamic, inclusion_matrix, inclusions, VectorTools::interpolate(), locally_relevant_solution, make_grid(), mass_matrix, output_results(), par, pcout, prec_C, prec_M, print_parameters(), refine_and_transfer(), setup_dofs(), setup_fe(), solution, solve_newmark(), stiffness_matrix, system_rhs, time_step, tria, and velocity.
Referenced by run().
run_quasistatic()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::run_quasistatic ()
Definition at line 1984 of file elasticity.cc.
References assemble_coupling(), assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), compute_system_rhs(), computing_timer, current_time, cycle, inclusions, make_grid(), output_results(), par, pcout, print_parameters(), QuasiStatic, refine_and_transfer(), setup_dofs(), setup_fe(), solve_quasistatic(), time_step, and tria.
Referenced by run().
run_static()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::run_static ()
Internal run implementations selected by time_mode.
run_static(): stationary solve with optional refinement cycles.
run_quasistatic(): time-dependent run without inertia (currently solve_quasistatic() is not implemented).
run_newmark(): time-dependent run with inertia (Newmark).
Definition at line 1930 of file elasticity.cc.
References assemble_coupling(), assemble_elasticity_system(), compute_internal_and_boundary_stress(), computing_timer, current_time, cycle, dh, inclusions, locally_relevant_solution, make_grid(), output_lambda(), output_results(), par, pcout, print_parameters(), refine_and_transfer(), setup_dofs(), setup_fe(), solve_static(), Static, time_step, and tria.
Referenced by run().
setup_dofs()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::setup_dofs ()
Definition at line 172 of file elasticity.cc.
References acceleration, DynamicSparsityPattern::add(), assemble_coupling_sparsity(), bc_rhs, VectorTools::compute_nonzero_normal_flux_constraints(), computing_timer, constraints, corrector, coupling_matrix, Utilities::MPI::create_evenly_distributed_partitioning(), damping_matrix, dh, SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), face_quadrature_formula, fe, force_rhs, inclusion_constraints, inclusion_matrix, inclusions, VectorTools::interpolate_boundary_values(), locally_relevant_solution, DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), mass_matrix, mpi_communicator, neumann_bc_rhs, newmark_matrix, owned_dofs, par, pcout, predictor, relevant_dofs, solution, Static, stiffness_matrix, system_rhs, and velocity.
Referenced by execute_actual_refine_and_transfer(), run_newmark(), run_quasistatic(), and run_static().
setup_fe()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::setup_fe ()
Definition at line 158 of file elasticity.cc.
References computing_timer, face_quadrature_formula, fe, par, and quadrature.
Referenced by run_newmark(), run_quasistatic(), and run_static().
solve()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::solve ()
Definition at line 1025 of file elasticity.cc.
References Dynamic, par, QuasiStatic, solve_newmark(), solve_quasistatic(), solve_static(), and Static.
solve_newmark()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::solve_newmark ()
Definition at line 1288 of file elasticity.cc.
References acceleration, computing_timer, constraints, corrector, coupling_matrix, damping_matrix, inclusion_constraints, inclusion_matrix, inclusions, KelvinVoigt, LinearElasticity, locally_relevant_solution, newmark_matrix, par, pcout, prec_M, prec_newmark, predictor, solution, stiffness_matrix, system_rhs, and velocity.
Referenced by run_newmark(), and solve().
solve_quasistatic()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::solve_quasistatic ()
Definition at line 1258 of file elasticity.cc.
References computing_timer, constraints, inclusions, locally_relevant_solution, par, pcout, prec_A, solution, stiffness_matrix, and system_rhs.
Referenced by run_quasistatic(), and solve().
solve_static()
template<int dim, int spacedim> void ElasticityProblem< dim, spacedim >::solve_static ()
Internal solver implementations selected by time_mode.
Augmented the (1,1) block
augmented
Definition at line 1045 of file elasticity.cc.
References computing_timer, SolverCG< typename VectorType >::connect_condition_number_slot(), constraints, coupling_matrix, inclusion_constraints, inclusion_matrix, inclusions, locally_relevant_solution, output_double_number(), par, pcout, prec_A, prec_M, solution, SolverCG< typename VectorType >::solve(), SolverFGMRES< typename VectorType >::solve(), stiffness_matrix, and system_rhs.
Referenced by run_static(), and solve().
Member Data Documentation
acceleration
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::acceleration
Definition at line 541 of file elasticity.h.
Referenced by run_newmark(), setup_dofs(), and solve_newmark().
areas
template<int dim, int spacedim = dim> std::map<types::boundary_id, double> ElasticityProblem< dim, spacedim >::areas
Definition at line 559 of file elasticity.h.
average_displacements
template<int dim, int spacedim = dim> std::map<types::boundary_id, Tensor<1, spacedim> > ElasticityProblem< dim, spacedim >::average_displacements
Definition at line 557 of file elasticity.h.
average_normals
template<int dim, int spacedim = dim> std::map<types::boundary_id, Tensor<1, spacedim> > ElasticityProblem< dim, spacedim >::average_normals
Definition at line 558 of file elasticity.h.
bc_rhs
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::bc_rhs
Definition at line 546 of file elasticity.h.
Referenced by assemble_forcing_terms(), compute_system_rhs(), and setup_dofs().
computing_timer
template<int dim, int spacedim = dim> TimerOutput ElasticityProblem< dim, spacedim >::computing_timer mutable
Definition at line 513 of file elasticity.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), ElasticityProblem(), output_results(), refine_and_transfer(), run_newmark(), run_quasistatic(), run_static(), setup_dofs(), setup_fe(), solve_newmark(), solve_quasistatic(), and solve_static().
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> ElasticityProblem< dim, spacedim >::constraints
Definition at line 523 of file elasticity.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_elasticity_system(), assemble_forcing_terms(), execute_actual_refine_and_transfer(), output_solution(), run_newmark(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
corrector
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::corrector
Definition at line 543 of file elasticity.h.
Referenced by setup_dofs(), and solve_newmark().
coupling_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ElasticityProblem< dim, spacedim >::coupling_matrix
Definition at line 530 of file elasticity.h.
Referenced by assemble_coupling(), assemble_elasticity_system(), run_newmark(), setup_dofs(), solve_newmark(), and solve_static().
current_time
template<int dim, int spacedim = dim> double ElasticityProblem< dim, spacedim >::current_time = 0.0
Definition at line 564 of file elasticity.h.
Referenced by assemble_elasticity_system(), assemble_forcing_terms(), compute_system_rhs(), output_results(), output_solution(), run_newmark(), run_quasistatic(), and run_static().
cycle
template<int dim, int spacedim = dim> unsigned int ElasticityProblem< dim, spacedim >::cycle = 0
Definition at line 550 of file elasticity.h.
Referenced by compute_internal_and_boundary_stress(), output_results(), output_solution(), run_newmark(), run_quasistatic(), and run_static().
damping_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ElasticityProblem< dim, spacedim >::damping_matrix
Definition at line 531 of file elasticity.h.
Referenced by assemble_elasticity_system(), run_newmark(), setup_dofs(), and solve_newmark().
dh
template<int dim, int spacedim = dim> DoFHandler<spacedim> ElasticityProblem< dim, spacedim >::dh
Definition at line 519 of file elasticity.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), ElasticityProblem(), execute_actual_refine_and_transfer(), output_solution(), refine_and_transfer(), run_newmark(), run_static(), and setup_dofs().
displacement
template<int dim, int spacedim = dim> FEValuesExtractors::Vector ElasticityProblem< dim, spacedim >::displacement
Definition at line 553 of file elasticity.h.
Referenced by assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), and ElasticityProblem().
face_quadrature_formula
template<int dim, int spacedim = dim> std::unique_ptr<Quadrature<spacedim - 1> > ElasticityProblem< dim, spacedim >::face_quadrature_formula
Definition at line 518 of file elasticity.h.
Referenced by assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), setup_dofs(), and setup_fe().
fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<spacedim> > ElasticityProblem< dim, spacedim >::fe
Definition at line 515 of file elasticity.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), setup_dofs(), and setup_fe().
force_rhs
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::force_rhs
Definition at line 545 of file elasticity.h.
Referenced by assemble_coupling(), assemble_forcing_terms(), compute_system_rhs(), and setup_dofs().
forces
template<int dim, int spacedim = dim> std::map<types::boundary_id, Tensor<1, spacedim> > ElasticityProblem< dim, spacedim >::forces
Definition at line 556 of file elasticity.h.
global_bounding_boxes
template<int dim, int spacedim = dim> std::vector<std::vector<BoundingBox<spacedim> > > ElasticityProblem< dim, spacedim >::global_bounding_boxes
Definition at line 549 of file elasticity.h.
inclusion_constraints
template<int dim, int spacedim = dim> AffineConstraints<double> ElasticityProblem< dim, spacedim >::inclusion_constraints
Definition at line 524 of file elasticity.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), setup_dofs(), solve_newmark(), and solve_static().
inclusion_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ElasticityProblem< dim, spacedim >::inclusion_matrix
Definition at line 538 of file elasticity.h.
Referenced by assemble_coupling(), run_newmark(), setup_dofs(), solve_newmark(), and solve_static().
inclusions
template<int dim, int spacedim = dim> Inclusions<spacedim> ElasticityProblem< dim, spacedim >::inclusions
Definition at line 516 of file elasticity.h.
Referenced by assemble_coupling(), assemble_coupling_sparsity(), compute_system_rhs(), ElasticityProblem(), execute_actual_refine_and_transfer(), output_lambda(), output_results(), run_newmark(), run_quasistatic(), run_static(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
locally_relevant_solution
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::locally_relevant_solution
Definition at line 544 of file elasticity.h.
Referenced by compute_internal_and_boundary_stress(), execute_actual_refine_and_transfer(), output_lambda(), output_solution(), refine_and_transfer(), run_newmark(), run_static(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
mass_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ElasticityProblem< dim, spacedim >::mass_matrix
Definition at line 529 of file elasticity.h.
Referenced by assemble_elasticity_system(), run_newmark(), and setup_dofs().
mean_value_constraints
template<int dim, int spacedim = dim> AffineConstraints<double> ElasticityProblem< dim, spacedim >::mean_value_constraints
Definition at line 525 of file elasticity.h.
mpi_communicator
template<int dim, int spacedim = dim> MPI_Comm ElasticityProblem< dim, spacedim >::mpi_communicator
Definition at line 511 of file elasticity.h.
Referenced by assemble_elasticity_system(), compute_internal_and_boundary_stress(), ElasticityProblem(), output_solution(), and setup_dofs().
neumann_bc_rhs
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::neumann_bc_rhs
Definition at line 547 of file elasticity.h.
Referenced by assemble_forcing_terms(), compute_system_rhs(), and setup_dofs().
newmark_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ElasticityProblem< dim, spacedim >::newmark_matrix
Definition at line 528 of file elasticity.h.
Referenced by assemble_elasticity_system(), setup_dofs(), and solve_newmark().
owned_dofs
template<int dim, int spacedim = dim> std::vector<IndexSet> ElasticityProblem< dim, spacedim >::owned_dofs
Definition at line 520 of file elasticity.h.
Referenced by setup_dofs().
par
template<int dim, int spacedim = dim> const ElasticityProblemParameters<dim, spacedim>& ElasticityProblem< dim, spacedim >::par
Definition at line 510 of file elasticity.h.
Referenced by assemble_coupling(), assemble_elasticity_system(), assemble_forcing_terms(), compute_internal_and_boundary_stress(), compute_system_rhs(), ElasticityProblem(), make_grid(), output_lambda(), output_results(), output_solution(), print_parameters(), refine_and_transfer(), run(), run_newmark(), run_quasistatic(), run_static(), setup_dofs(), setup_fe(), solve(), solve_newmark(), solve_quasistatic(), and solve_static().
pcout
template<int dim, int spacedim = dim> ConditionalOStream ElasticityProblem< dim, spacedim >::pcout
Definition at line 512 of file elasticity.h.
Referenced by compute_system_rhs(), ElasticityProblem(), make_grid(), print_parameters(), run_newmark(), run_quasistatic(), run_static(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
prec_A
template<int dim, int spacedim = dim> LA::MPI::PreconditionAMG ElasticityProblem< dim, spacedim >::prec_A
Definition at line 533 of file elasticity.h.
Referenced by assemble_elasticity_system(), solve_quasistatic(), and solve_static().
prec_C
template<int dim, int spacedim = dim> LA::MPI::PreconditionAMG ElasticityProblem< dim, spacedim >::prec_C
Definition at line 535 of file elasticity.h.
Referenced by assemble_elasticity_system(), and run_newmark().
prec_M
template<int dim, int spacedim = dim> LA::MPI::PreconditionAMG ElasticityProblem< dim, spacedim >::prec_M
Definition at line 536 of file elasticity.h.
Referenced by assemble_coupling(), run_newmark(), solve_newmark(), and solve_static().
prec_newmark
template<int dim, int spacedim = dim> LA::MPI::PreconditionAMG ElasticityProblem< dim, spacedim >::prec_newmark
Definition at line 534 of file elasticity.h.
Referenced by assemble_elasticity_system(), and solve_newmark().
predictor
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::predictor
Definition at line 542 of file elasticity.h.
Referenced by setup_dofs(), and solve_newmark().
quadrature
template<int dim, int spacedim = dim> std::unique_ptr<Quadrature<spacedim> > ElasticityProblem< dim, spacedim >::quadrature
Definition at line 517 of file elasticity.h.
Referenced by assemble_elasticity_system(), assemble_forcing_terms(), and setup_fe().
relevant_dofs
template<int dim, int spacedim = dim> std::vector<IndexSet> ElasticityProblem< dim, spacedim >::relevant_dofs
Definition at line 521 of file elasticity.h.
Referenced by setup_dofs().
sigma_n
template<int dim, int spacedim = dim> TrilinosWrappers::MPI::Vector ElasticityProblem< dim, spacedim >::sigma_n
Definition at line 560 of file elasticity.h.
solution
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::solution
Definition at line 539 of file elasticity.h.
Referenced by execute_actual_refine_and_transfer(), output_solution(), run_newmark(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
stiffness_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ElasticityProblem< dim, spacedim >::stiffness_matrix
Definition at line 527 of file elasticity.h.
Referenced by assemble_elasticity_system(), run_newmark(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
system_rhs
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::system_rhs
Definition at line 548 of file elasticity.h.
Referenced by assemble_coupling(), assemble_elasticity_system(), assemble_forcing_terms(), compute_system_rhs(), run_newmark(), setup_dofs(), solve_newmark(), solve_quasistatic(), and solve_static().
time_step
template<int dim, int spacedim = dim> unsigned int ElasticityProblem< dim, spacedim >::time_step = 0
Definition at line 551 of file elasticity.h.
Referenced by compute_internal_and_boundary_stress(), output_results(), output_solution(), run_newmark(), run_quasistatic(), and run_static().
tria
template<int dim, int spacedim = dim> parallel::distributed::Triangulation<spacedim> ElasticityProblem< dim, spacedim >::tria
Definition at line 514 of file elasticity.h.
Referenced by compute_internal_and_boundary_stress(), ElasticityProblem(), execute_actual_refine_and_transfer(), make_grid(), output_solution(), refine_and_transfer(), run_newmark(), run_quasistatic(), and run_static().
velocity
template<int dim, int spacedim = dim> LA::MPI::BlockVector ElasticityProblem< dim, spacedim >::velocity
Definition at line 540 of file elasticity.h.
Referenced by run_newmark(), setup_dofs(), and solve_newmark().
The documentation for this class was generated from the following files:
/github/workspace/include/elasticity.h
/github/workspace/source/elasticity.cc