Reduced Lagrange Multipliers: ReducedPoisson< dim, spacedim > Class Template Reference
ReducedPoisson< dim, spacedim > Class Template Reference
#include <reduced_poisson.h>
Public Member Functions
ReducedPoisson (const ReducedPoissonParameters< spacedim > &par)
void make_grid ()
void setup_fe ()
void setup_dofs ()
void assemble_poisson_system ()
void run ()
void solve ()
void refine_and_transfer ()
std::string output_solution () const
void output_results () const
void print_parameters () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Private Types
using VectorType = LA::MPI::Vector
using BlockVectorType = LA::MPI::BlockVector
Private Attributes
const ReducedPoissonParameters< spacedim > & par
MPI_Comm mpi_communicator
ConditionalOStream pcout
TimerOutput computing_timer
parallel::distributed::Triangulation< spacedim > tria
std::unique_ptr< FiniteElement< spacedim > > fe
std::unique_ptr< Quadrature< spacedim > > quadrature
DoFHandler< spacedim > dh
ReducedCoupling< 1, 2, spacedim, 1 > reduced_coupling
std::vector< IndexSet > owned_dofs
std::vector< IndexSet > relevant_dofs
AffineConstraints< double > constraints
LA::MPI::SparseMatrix coupling_matrix
LA::MPI::SparseMatrix coupling_matrix_transpose
LA::MPI::SparseMatrix inclusion_matrix
MappingQ< spacedim > mapping
LA::MPI::SparseMatrix stiffness_matrix
BlockVectorType solution
BlockVectorType locally_relevant_solution
BlockVectorType system_rhs
std::vector< std::vector< BoundingBox< spacedim > > > global_bounding_boxes
unsigned int cycle = 0
Additional Inherited Members
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Detailed Description
template<int dim, int spacedim = dim>
class ReducedPoisson< dim, spacedim >
Definition at line 154 of file reduced_poisson.h.
Member Typedef Documentation
BlockVectorType
template<int dim, int spacedim = dim> using ReducedPoisson< dim, spacedim >::BlockVectorType = LA::MPI::BlockVector private
Definition at line 228 of file reduced_poisson.h.
VectorType
template<int dim, int spacedim = dim> using ReducedPoisson< dim, spacedim >::VectorType = LA::MPI::Vector private
Definition at line 227 of file reduced_poisson.h.
Constructor & Destructor Documentation
ReducedPoisson()
template<int dim, int spacedim> ReducedPoisson< dim, spacedim >::ReducedPoisson (const ReducedPoissonParameters< spacedim > & par)
Definition at line 87 of file reduced_poisson.cc.
References computing_timer, dh, mapping, mpi_communicator, par, pcout, reduced_coupling, and tria.
Member Function Documentation
assemble_poisson_system()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::assemble_poisson_system ()
Definition at line 336 of file reduced_poisson.cc.
References VectorOperation::add, constraints, coupling_matrix, dh, fe, FEValues< int dim, int spacedim >::get_quadrature_points(), FEValues< int dim, int spacedim >::JxW(), par, quadrature, FEValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::shape_value(), stiffness_matrix, and system_rhs.
Referenced by run().
make_grid()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::make_grid ()
Definition at line 163 of file reduced_poisson.cc.
References GridGenerator::generate_from_name_and_arguments(), par, pcout, read_grid_and_cad_files(), and tria.
Referenced by run().
output_results()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::output_results () const
Definition at line 932 of file reduced_poisson.cc.
References cycle, output_solution(), par, reduced_coupling, and DataOutBase::write_pvd_record().
Referenced by run().
output_solution()
template<int dim, int spacedim> std::string ReducedPoisson< dim, spacedim >::output_solution () const
Definition at line 910 of file reduced_poisson.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), computing_timer, cycle, dh, locally_relevant_solution, mpi_communicator, par, Vector< typename Number >::size(), tria, and DataOut< int dim, int spacedim >::write_vtu_in_parallel().
Referenced by output_results().
print_parameters()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::print_parameters () const
Definition at line 959 of file reduced_poisson.cc.
References Utilities::dim_string(), mpi_communicator, Utilities::MPI::n_mpi_processes(), par, pcout, ParameterHandler::Short, and Utilities::MPI::this_mpi_process().
Referenced by run().
refine_and_transfer()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::refine_and_transfer ()
Definition at line 865 of file reduced_poisson.cc.
References computing_timer, constraints, dh, KellyErrorEstimator< int dim, int spacedim >::estimate(), SolutionTransfer< int dim, typename VectorType, int spacedim >::interpolate(), locally_relevant_solution, par, SolutionTransfer< int dim, typename VectorType, int spacedim >::prepare_for_coarsening_and_refinement(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_fraction(), parallel::distributed::GridRefinement::refine_and_coarsen_fixed_number(), setup_dofs(), solution, and tria.
Referenced by run().
run()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::run ()
Definition at line 981 of file reduced_poisson.cc.
References assemble_poisson_system(), constraints, coupling_matrix, cycle, dh, locally_relevant_solution, make_grid(), output_results(), par, pcout, print_parameters(), reduced_coupling, refine_and_transfer(), setup_dofs(), setup_fe(), solve(), and system_rhs.
setup_dofs()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::setup_dofs ()
Definition at line 194 of file reduced_poisson.cc.
References AffineConstraints< typename number >::close(), computing_timer, AffineConstraints< typename number >::constrain_dof_to_zero(), constraints, coupling_matrix, dh, SparsityTools::distribute_sparsity_pattern(), DoFTools::extract_locally_relevant_dofs(), DoFTools::extract_locally_relevant_level_dofs(), fe, VectorTools::interpolate_boundary_values(), locally_relevant_solution, DoFTools::make_hanging_node_constraints(), DoFTools::make_sparsity_pattern(), mapping, MatrixFree::AdditionalData::mapping_update_flags, MatrixFree::AdditionalData::mg_level, mpi_communicator, MatrixFree::AdditionalData::none, owned_dofs, par, pcout, reduced_coupling, relevant_dofs, solution, stiffness_matrix, system_rhs, MatrixFree::AdditionalData::tasks_parallel_scheme, and tria.
Referenced by refine_and_transfer(), and run().
setup_fe()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::setup_fe ()
Definition at line 184 of file reduced_poisson.cc.
References computing_timer, fe, par, and quadrature.
Referenced by run().
solve()
template<int dim, int spacedim> void ReducedPoisson< dim, spacedim >::solve ()
Augmented the (1,1) block
Definition at line 543 of file reduced_poisson.cc.
References VectorOperation::add, MGTransferMatrixFree< int dim, typename Number >::build(), TrilinosWrappers::MPI::Vector::compress(), computing_timer, SolverCG< typename VectorType >::connect_condition_number_slot(), constraints, coupling_matrix, UtilitiesAL::create_augmented_block(), dh, SparsityTools::distribute_sparsity_pattern(), MGCoarseGridApplySmoother< typename VectorType >::initialize(), TrilinosWrappers::PreconditionAMG::initialize(), TrilinosWrappers::PreconditionILU::initialize(), VectorOperation::insert, numbers::invalid_unsigned_int, locally_relevant_solution, DoFTools::make_sparsity_pattern(), mpi_communicator, owned_dofs, par, pcout, reduced_coupling, TrilinosWrappers::MPI::Vector::reinit(), relevant_dofs, MGLevelObject< class Object >::resize(), solution, SolverCG< typename VectorType >::solve(), SolverFGMRES< typename VectorType >::solve(), stiffness_matrix, system_rhs, Utilities::MPI::this_mpi_process(), and tria.
Referenced by run().
Member Data Documentation
computing_timer
template<int dim, int spacedim = dim> TimerOutput ReducedPoisson< dim, spacedim >::computing_timer mutable private
Definition at line 193 of file reduced_poisson.h.
Referenced by output_solution(), ReducedPoisson(), refine_and_transfer(), setup_dofs(), setup_fe(), and solve().
constraints
template<int dim, int spacedim = dim> AffineConstraints<double> ReducedPoisson< dim, spacedim >::constraints private
Definition at line 206 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), refine_and_transfer(), run(), setup_dofs(), and solve().
coupling_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ReducedPoisson< dim, spacedim >::coupling_matrix private
Definition at line 208 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), run(), setup_dofs(), and solve().
coupling_matrix_transpose
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ReducedPoisson< dim, spacedim >::coupling_matrix_transpose private
Definition at line 209 of file reduced_poisson.h.
cycle
template<int dim, int spacedim = dim> unsigned int ReducedPoisson< dim, spacedim >::cycle = 0 private
Definition at line 235 of file reduced_poisson.h.
Referenced by output_results(), output_solution(), and run().
dh
template<int dim, int spacedim = dim> DoFHandler<spacedim> ReducedPoisson< dim, spacedim >::dh private
Definition at line 199 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), output_solution(), ReducedPoisson(), refine_and_transfer(), run(), setup_dofs(), and solve().
fe
template<int dim, int spacedim = dim> std::unique_ptr<FiniteElement<spacedim> > ReducedPoisson< dim, spacedim >::fe private
Definition at line 195 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), setup_dofs(), and setup_fe().
global_bounding_boxes
template<int dim, int spacedim = dim> std::vector<std::vector<BoundingBox<spacedim> > > ReducedPoisson< dim, spacedim >::global_bounding_boxes private
Definition at line 234 of file reduced_poisson.h.
inclusion_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ReducedPoisson< dim, spacedim >::inclusion_matrix private
Definition at line 210 of file reduced_poisson.h.
locally_relevant_solution
template<int dim, int spacedim = dim> BlockVectorType ReducedPoisson< dim, spacedim >::locally_relevant_solution private
Definition at line 232 of file reduced_poisson.h.
Referenced by output_solution(), refine_and_transfer(), run(), setup_dofs(), and solve().
mapping
template<int dim, int spacedim = dim> MappingQ<spacedim> ReducedPoisson< dim, spacedim >::mapping private
Definition at line 211 of file reduced_poisson.h.
Referenced by ReducedPoisson(), and setup_dofs().
mpi_communicator
template<int dim, int spacedim = dim> MPI_Comm ReducedPoisson< dim, spacedim >::mpi_communicator private
Definition at line 191 of file reduced_poisson.h.
Referenced by output_solution(), print_parameters(), ReducedPoisson(), setup_dofs(), and solve().
owned_dofs
template<int dim, int spacedim = dim> std::vector<IndexSet> ReducedPoisson< dim, spacedim >::owned_dofs private
Definition at line 203 of file reduced_poisson.h.
Referenced by setup_dofs(), and solve().
par
template<int dim, int spacedim = dim> const ReducedPoissonParameters<spacedim>& ReducedPoisson< dim, spacedim >::par private
Definition at line 190 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), make_grid(), output_results(), output_solution(), print_parameters(), ReducedPoisson(), refine_and_transfer(), run(), setup_dofs(), setup_fe(), and solve().
pcout
template<int dim, int spacedim = dim> ConditionalOStream ReducedPoisson< dim, spacedim >::pcout private
Definition at line 192 of file reduced_poisson.h.
Referenced by make_grid(), print_parameters(), ReducedPoisson(), run(), setup_dofs(), and solve().
quadrature
template<int dim, int spacedim = dim> std::unique_ptr<Quadrature<spacedim> > ReducedPoisson< dim, spacedim >::quadrature private
Definition at line 197 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), and setup_fe().
reduced_coupling
template<int dim, int spacedim = dim> ReducedCoupling<1, 2, spacedim, 1> ReducedPoisson< dim, spacedim >::reduced_coupling private
Definition at line 201 of file reduced_poisson.h.
Referenced by output_results(), ReducedPoisson(), run(), setup_dofs(), and solve().
relevant_dofs
template<int dim, int spacedim = dim> std::vector<IndexSet> ReducedPoisson< dim, spacedim >::relevant_dofs private
Definition at line 204 of file reduced_poisson.h.
Referenced by setup_dofs(), and solve().
solution
template<int dim, int spacedim = dim> BlockVectorType ReducedPoisson< dim, spacedim >::solution private
Definition at line 231 of file reduced_poisson.h.
Referenced by refine_and_transfer(), setup_dofs(), and solve().
stiffness_matrix
template<int dim, int spacedim = dim> LA::MPI::SparseMatrix ReducedPoisson< dim, spacedim >::stiffness_matrix private
Definition at line 226 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), setup_dofs(), and solve().
system_rhs
template<int dim, int spacedim = dim> BlockVectorType ReducedPoisson< dim, spacedim >::system_rhs private
Definition at line 233 of file reduced_poisson.h.
Referenced by assemble_poisson_system(), run(), setup_dofs(), and solve().
tria
template<int dim, int spacedim = dim> parallel::distributed::Triangulation<spacedim> ReducedPoisson< dim, spacedim >::tria private
Definition at line 194 of file reduced_poisson.h.
Referenced by make_grid(), output_solution(), ReducedPoisson(), refine_and_transfer(), setup_dofs(), and solve().
The documentation for this class was generated from the following files:
/github/workspace/include/reduced_poisson.h
/github/workspace/source/reduced_poisson.cc