Template Deal.II Application: /github/workspace/include/laplacian.h File Reference
laplacian.h File Reference
#include <deal.II/base/function.h>
#include <deal.II/base/quadrature_lib.h>
#include <deal.II/base/timer.h>
#include <deal.II/lac/block_linear_operator.h>
#include <deal.II/lac/generic_linear_algebra.h>
#include <deal.II/lac/linear_operator.h>
#include <deal.II/lac/linear_operator_tools.h>
#include <deal.II/base/conditional_ostream.h>
#include <deal.II/base/index_set.h>
#include <deal.II/base/parameter_acceptor.h>
#include <deal.II/base/parsed_function.h>
#include <deal.II/base/utilities.h>
#include <deal.II/distributed/grid_refinement.h>
#include <deal.II/distributed/solution_transfer.h>
#include <deal.II/distributed/tria.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/dofs/dof_renumbering.h>
#include <deal.II/dofs/dof_tools.h>
#include <deal.II/fe/fe_nothing.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_system.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_fe_field.h>
#include <deal.II/fe/mapping_q.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_tools.h>
#include <deal.II/grid/manifold_lib.h>
#include <deal.II/lac/affine_constraints.h>
#include <deal.II/lac/dynamic_sparsity_pattern.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/petsc_precondition.h>
#include <deal.II/lac/petsc_solver.h>
#include <deal.II/lac/petsc_sparse_matrix.h>
#include <deal.II/lac/petsc_vector.h>
#include <deal.II/lac/solver_cg.h>
#include <deal.II/lac/solver_gmres.h>
#include <deal.II/lac/solver_minres.h>
#include <deal.II/lac/sparsity_tools.h>
#include <deal.II/lac/vector.h>
#include <deal.II/numerics/data_out.h>
#include <deal.II/numerics/error_estimator.h>
#include <deal.II/numerics/vector_tools.h>
#include <deal.II/opencascade/manifold_lib.h>
#include <deal.II/opencascade/utilities.h>
#include "reference_inclusion.h"
#include <cmath>
#include <fstream>
#include <iostream>
#include <memory>
Classes
class ProblemParameters< dim, spacedim >
class PoissonProblem< dim, spacedim >
Namespaces
namespace LA
Macros
#define FORCE_USE_OF_TRILINOS
Functions
template<int dim, int spacedim>
void read_grid_and_cad_files (const std::string &grid_file_name, const std::string &ids_and_cad_file_names, Triangulation< dim, spacedim > &tria)
Macro Definition Documentation
FORCE_USE_OF_TRILINOS
#define FORCE_USE_OF_TRILINOS
Definition at line 14 of file laplacian.h.
Function Documentation
read_grid_and_cad_files()
template<int dim, int spacedim> void read_grid_and_cad_files (const std::string & grid_file_name, const std::string & ids_and_cad_file_names, Triangulation< dim, spacedim > & tria)
Definition at line 262 of file laplacian.h.
References AssertThrow, GridIn< dim, spacedim >::attach_triangulation(), OpenCASCADE::count_elements(), ExcNotImplemented(), GridIn< dim, spacedim >::read(), OpenCASCADE::read_IGES(), OpenCASCADE::read_STEP(), Triangulation< dim, spacedim >::set_manifold(), and tria.
Referenced by PoissonProblem< dim, spacedim >::make_grid().