Template Deal.II Application: /github/workspace/source/laplacian.cc File Reference
laplacian.cc File Reference
#include "laplacian.h"
Functions
template<int dim, int spacedim>
void read_grid_and_cad_files (const std::string &grid_file_name, const std::string &ids_and_cad_file_names, Triangulation< dim, spacedim > &tria)
Function Documentation
read_grid_and_cad_files()
template<int dim, int spacedim> void read_grid_and_cad_files (const std::string & grid_file_name, const std::string & ids_and_cad_file_names, Triangulation< dim, spacedim > & tria)
Definition at line 44 of file laplacian.cc.
References AssertThrow, GridIn< dim, spacedim >::attach_triangulation(), OpenCASCADE::count_elements(), GridIn< dim, spacedim >::read(), OpenCASCADE::read_IGES(), OpenCASCADE::read_STEP(), Triangulation< dim, spacedim >::set_manifold(), and tria.
Referenced by PoissonProblem< dim, spacedim >::make_grid().