# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /calculate/RLM_PR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /calculate/RLM_PR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /calculate/RLM_PR/CMakeFiles /calculate/RLM_PR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /calculate/RLM_PR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reduced_lagrange_lib_debug

# Build rule for target.
reduced_lagrange_lib_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reduced_lagrange_lib_debug
.PHONY : reduced_lagrange_lib_debug

# fast build rule for target.
reduced_lagrange_lib_debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/build
.PHONY : reduced_lagrange_lib_debug/fast

#=============================================================================
# Target rules for targets named elasticity_debug

# Build rule for target.
elasticity_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elasticity_debug
.PHONY : elasticity_debug

# fast build rule for target.
elasticity_debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elasticity_debug.dir/build.make CMakeFiles/elasticity_debug.dir/build
.PHONY : elasticity_debug/fast

#=============================================================================
# Target rules for targets named laplacian_debug

# Build rule for target.
laplacian_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laplacian_debug
.PHONY : laplacian_debug

# fast build rule for target.
laplacian_debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_debug.dir/build.make CMakeFiles/laplacian_debug.dir/build
.PHONY : laplacian_debug/fast

#=============================================================================
# Target rules for targets named indent

# Build rule for target.
indent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 indent
.PHONY : indent

# fast build rule for target.
indent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/indent.dir/build.make CMakeFiles/indent.dir/build
.PHONY : indent/fast

#=============================================================================
# Target rules for targets named compile_test_executables

# Build rule for target.
compile_test_executables: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_test_executables
.PHONY : compile_test_executables

# fast build rule for target.
compile_test_executables/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/compile_test_executables.dir/build.make tests/CMakeFiles/compile_test_executables.dir/build
.PHONY : compile_test_executables/fast

#=============================================================================
# Target rules for targets named tests.template.debug

# Build rule for target.
tests.template.debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.template.debug
.PHONY : tests.template.debug

# fast build rule for target.
tests.template.debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.template.debug.dir/build.make tests/CMakeFiles/tests.template.debug.dir/build
.PHONY : tests.template.debug/fast

#=============================================================================
# Target rules for targets named tests.template.debug.test

# Build rule for target.
tests.template.debug.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.template.debug.test
.PHONY : tests.template.debug.test

# fast build rule for target.
tests.template.debug.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.template.debug.test.dir/build.make tests/CMakeFiles/tests.template.debug.test.dir/build
.PHONY : tests.template.debug.test/fast

#=============================================================================
# Target rules for targets named tests.test_fourier_01.debug

# Build rule for target.
tests.test_fourier_01.debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.test_fourier_01.debug
.PHONY : tests.test_fourier_01.debug

# fast build rule for target.
tests.test_fourier_01.debug/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.test_fourier_01.debug.dir/build.make tests/CMakeFiles/tests.test_fourier_01.debug.dir/build
.PHONY : tests.test_fourier_01.debug/fast

#=============================================================================
# Target rules for targets named tests.test_fourier_01.debug.test

# Build rule for target.
tests.test_fourier_01.debug.test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tests.test_fourier_01.debug.test
.PHONY : tests.test_fourier_01.debug.test

# fast build rule for target.
tests.test_fourier_01.debug.test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/tests.test_fourier_01.debug.test.dir/build.make tests/CMakeFiles/tests.test_fourier_01.debug.test.dir/build
.PHONY : tests.test_fourier_01.debug.test/fast

apps/app_elasticity.o: apps/app_elasticity.cc.o
.PHONY : apps/app_elasticity.o

# target to build an object file
apps/app_elasticity.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elasticity_debug.dir/build.make CMakeFiles/elasticity_debug.dir/apps/app_elasticity.cc.o
.PHONY : apps/app_elasticity.cc.o

apps/app_elasticity.i: apps/app_elasticity.cc.i
.PHONY : apps/app_elasticity.i

# target to preprocess a source file
apps/app_elasticity.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elasticity_debug.dir/build.make CMakeFiles/elasticity_debug.dir/apps/app_elasticity.cc.i
.PHONY : apps/app_elasticity.cc.i

apps/app_elasticity.s: apps/app_elasticity.cc.s
.PHONY : apps/app_elasticity.s

# target to generate assembly for a file
apps/app_elasticity.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elasticity_debug.dir/build.make CMakeFiles/elasticity_debug.dir/apps/app_elasticity.cc.s
.PHONY : apps/app_elasticity.cc.s

apps/app_laplacian.o: apps/app_laplacian.cc.o
.PHONY : apps/app_laplacian.o

# target to build an object file
apps/app_laplacian.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_debug.dir/build.make CMakeFiles/laplacian_debug.dir/apps/app_laplacian.cc.o
.PHONY : apps/app_laplacian.cc.o

apps/app_laplacian.i: apps/app_laplacian.cc.i
.PHONY : apps/app_laplacian.i

# target to preprocess a source file
apps/app_laplacian.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_debug.dir/build.make CMakeFiles/laplacian_debug.dir/apps/app_laplacian.cc.i
.PHONY : apps/app_laplacian.cc.i

apps/app_laplacian.s: apps/app_laplacian.cc.s
.PHONY : apps/app_laplacian.s

# target to generate assembly for a file
apps/app_laplacian.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/laplacian_debug.dir/build.make CMakeFiles/laplacian_debug.dir/apps/app_laplacian.cc.s
.PHONY : apps/app_laplacian.cc.s

source/elasticity.o: source/elasticity.cc.o
.PHONY : source/elasticity.o

# target to build an object file
source/elasticity.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/source/elasticity.cc.o
.PHONY : source/elasticity.cc.o

source/elasticity.i: source/elasticity.cc.i
.PHONY : source/elasticity.i

# target to preprocess a source file
source/elasticity.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/source/elasticity.cc.i
.PHONY : source/elasticity.cc.i

source/elasticity.s: source/elasticity.cc.s
.PHONY : source/elasticity.s

# target to generate assembly for a file
source/elasticity.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/source/elasticity.cc.s
.PHONY : source/elasticity.cc.s

source/laplacian.o: source/laplacian.cc.o
.PHONY : source/laplacian.o

# target to build an object file
source/laplacian.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/source/laplacian.cc.o
.PHONY : source/laplacian.cc.o

source/laplacian.i: source/laplacian.cc.i
.PHONY : source/laplacian.i

# target to preprocess a source file
source/laplacian.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/source/laplacian.cc.i
.PHONY : source/laplacian.cc.i

source/laplacian.s: source/laplacian.cc.s
.PHONY : source/laplacian.s

# target to generate assembly for a file
source/laplacian.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reduced_lagrange_lib_debug.dir/build.make CMakeFiles/reduced_lagrange_lib_debug.dir/source/laplacian.cc.s
.PHONY : source/laplacian.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... compile_test_executables"
	@echo "... indent"
	@echo "... tests.template.debug.test"
	@echo "... tests.test_fourier_01.debug.test"
	@echo "... elasticity_debug"
	@echo "... laplacian_debug"
	@echo "... reduced_lagrange_lib_debug"
	@echo "... tests.template.debug"
	@echo "... tests.test_fourier_01.debug"
	@echo "... apps/app_elasticity.o"
	@echo "... apps/app_elasticity.i"
	@echo "... apps/app_elasticity.s"
	@echo "... apps/app_laplacian.o"
	@echo "... apps/app_laplacian.i"
	@echo "... apps/app_laplacian.s"
	@echo "... source/elasticity.o"
	@echo "... source/elasticity.i"
	@echo "... source/elasticity.s"
	@echo "... source/laplacian.o"
	@echo "... source/laplacian.i"
	@echo "... source/laplacian.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

