Reduced Lagrange Multipliers: ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components > Class Template Reference
ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components > Class Template Reference
Parameter structure for configuring ReducedCoupling objects.
#include <reduced_coupling.h>
Public Member Functions
ReducedCouplingParameters ()
Constructor that registers parameters with the ParameterAcceptor.
Public Member Functions inherited from ParameterAcceptor
ParameterAcceptor (const std::string &section_name="")
unsigned int get_acceptor_id () const
virtual ~ParameterAcceptor () override
virtual void declare_parameters (ParameterHandler &prm)
virtual void parse_parameters (ParameterHandler &prm)
std::string get_section_name () const
std::vector< std::string > get_section_path () const
void add_parameter (const std::string &entry, ParameterType &parameter, const std::string &documentation="", ParameterHandler &prm_=prm, const Patterns::PatternBase &pattern=*Patterns::Tools::Convert< ParameterType >::to_pattern())
void enter_subsection (const std::string &subsection)
void leave_subsection ()
void enter_my_subsection (ParameterHandler &prm)
void leave_my_subsection (ParameterHandler &prm)
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Member Functions inherited from EnableObserverPointer
EnableObserverPointer ()
EnableObserverPointer (const EnableObserverPointer &)
EnableObserverPointer (EnableObserverPointer &&) noexcept
virtual ~EnableObserverPointer ()
EnableObserverPointer & operator= (const EnableObserverPointer &)
EnableObserverPointer & operator= (EnableObserverPointer &&) noexcept
void serialize (Archive &ar, const unsigned int version)
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
unsigned int n_subscriptions () const
void list_subscribers (StreamType &stream) const
void list_subscribers () const
Public Attributes
TensorProductSpaceParameters< reduced_dim, dim, spacedim, n_components > tensor_product_space_parameters
Parameters for the tensor product space.
ParticleCouplingParameters< spacedim > particle_coupling_parameters
Parameters for the particle coupling.
std::string reduced_grid_name = ""
Name of the grid to read from a file.
std::string radius_field_name = ""
unsigned int pre_refinement = 0
Number of pre-refinements to apply to the grid before distribution.
std::vector< std::string > coupling_rhs_expressions = {"0"}
Right hand side expressions for the reduced coupling.
Public Attributes inherited from ParameterAcceptor
boost::signals2::signal< void()> declare_parameters_call_back
boost::signals2::signal< void()> parse_parameters_call_back
Additional Inherited Members
Static Public Member Functions inherited from ParameterAcceptor
static void initialize (const std::string &filename="", const std::string &output_filename="", const ParameterHandler::OutputStyle output_style_for_output_filename=ParameterHandler::Short, ParameterHandler &prm=ParameterAcceptor::prm, const ParameterHandler::OutputStyle output_style_for_filename=ParameterHandler::DefaultStyle)
static void initialize (std::istream &input_stream, ParameterHandler &prm=ParameterAcceptor::prm)
static void clear ()
static void parse_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static void declare_all_parameters (ParameterHandler &prm=ParameterAcceptor::prm)
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Member Functions inherited from EnableObserverPointer
static ::ExceptionBase & ExcInUse (int arg1, std::string arg2, std::string arg3)
static ::ExceptionBase & ExcNoSubscriber (std::string arg1, std::string arg2)
Static Public Attributes inherited from ParameterAcceptor
static ParameterHandler prm
Protected Attributes inherited from ParameterAcceptor
const std::string section_name
std::vector< std::string > subsections
Detailed Description
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1>
class ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >
Parameter structure for configuring ReducedCoupling objects.
This structure holds all parameters required to set up a ReducedCoupling object, including parameters for the tensor product space, particle coupling, grid name, pre-refinement steps, and right-hand side expressions for the coupling.
Template Parameters
reduced_dim The reduced dimension of the problem.
dim The dimension of the domain we are approximating.
spacedim The space dimension (default: dim).
n_components Number of components (default: 1).
Definition at line 64 of file reduced_coupling.h.
Constructor & Destructor Documentation
ReducedCouplingParameters()
template<int reduced_dim, int dim, int spacedim, int n_components> ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::ReducedCouplingParameters ()
Constructor that registers parameters with the ParameterAcceptor.
Definition at line 13 of file reduced_coupling.cc.
References ParameterAcceptor::add_parameter(), coupling_rhs_expressions, ParameterAcceptor::enter_subsection(), ParameterAcceptor::leave_subsection(), Patterns::List::max_int_value, ParameterAcceptor::ParameterAcceptor(), pre_refinement, ParameterAcceptor::prm, and reduced_grid_name.
Member Data Documentation
coupling_rhs_expressions
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1> std::vector<std::string> ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::coupling_rhs_expressions = {"0"}
Right hand side expressions for the reduced coupling.
Definition at line 102 of file reduced_coupling.h.
Referenced by ReducedCouplingParameters().
particle_coupling_parameters
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1> ParticleCouplingParameters<spacedim> ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::particle_coupling_parameters
Parameters for the particle coupling.
Definition at line 80 of file reduced_coupling.h.
pre_refinement
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1> unsigned int ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::pre_refinement = 0
Number of pre-refinements to apply to the grid before distribution.
Definition at line 97 of file reduced_coupling.h.
Referenced by ReducedCouplingParameters().
radius_field_name
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1> std::string ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::radius_field_name = ""
Name of the field name to use for the radius of the inclusion. This is read from the reduced_grid_name file. If empty, the radius is assumed to be constant, and taken from the tensor_product_space_parameters.
Definition at line 92 of file reduced_coupling.h.
reduced_grid_name
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1> std::string ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::reduced_grid_name = ""
Name of the grid to read from a file.
Definition at line 85 of file reduced_coupling.h.
Referenced by ReducedCouplingParameters().
tensor_product_space_parameters
template<int reduced_dim, int dim, int spacedim = dim, int n_components = 1> TensorProductSpaceParameters<reduced_dim, dim, spacedim, n_components> ReducedCouplingParameters< reduced_dim, dim, spacedim, n_components >::tensor_product_space_parameters
Parameters for the tensor product space.
Definition at line 75 of file reduced_coupling.h.
The documentation for this class was generated from the following files:
/github/workspace/include/reduced_coupling.h
/github/workspace/source/reduced_coupling.cc