var searchData=
[
  ['data_0',['Data',['http://www.dealii.org/developer/doxygen/deal.II/structPortable_1_1MatrixFree_1_1Data.html',1,'Portable::MatrixFree']]],
  ['dataentrybase_1',['DataEntryBase',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DataOutImplementation_1_1DataEntryBase.html',1,'internal::DataOutImplementation']]],
  ['datahost_2',['DataHost',['http://www.dealii.org/developer/doxygen/deal.II/structPortable_1_1DataHost.html',1,'Portable']]],
  ['dataout_3',['DataOut',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'DataOut&lt; int dim, int spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classParticles_1_1DataOut.html',1,'Particles::DataOut&lt; int dim, int spacedim &gt;']]],
  ['dataout_3c_20dim_20_3e_4',['DataOut&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'']]],
  ['dataout_3c_20patch_5fdim_2c_20spacedim_20_3e_5',['DataOut&lt; patch_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'']]],
  ['dataout_5fdofdata_6',['DataOut_DoFData',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20patch_5fdim_2c_20spacedim_2c_20spacedim_20_3e_7',['DataOut_DoFData&lt; dim, patch_dim, spacedim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataoutfaces_8',['DataOutFaces',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutFaces.html',1,'']]],
  ['dataoutfilter_9',['DataOutFilter',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutBase_1_1DataOutFilter.html',1,'DataOutBase']]],
  ['dataoutfilterflags_10',['DataOutFilterFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DataOutFilterFlags.html',1,'DataOutBase']]],
  ['dataoutinterface_11',['DataOutInterface',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_201_2c_20spacedim_20_3e_12',['DataOutInterface&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_202_2c_202_20_3e_13',['DataOutInterface&lt; 2, 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2c_20dim_20_3e_14',['DataOutInterface&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutpoints_15',['DataOutPoints',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutPoints.html',1,'']]],
  ['dataoutreader_16',['DataOutReader',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutReader.html',1,'']]],
  ['dataoutresample_17',['DataOutResample',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutResample.html',1,'']]],
  ['dataoutrotation_18',['DataOutRotation',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutRotation.html',1,'']]],
  ['dataoutstack_19',['DataOutStack',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack.html',1,'']]],
  ['datapostprocessor_20',['DataPostprocessor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessorscalar_21',['DataPostprocessorScalar',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorScalar.html',1,'']]],
  ['datapostprocessortensor_22',['DataPostprocessorTensor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorTensor.html',1,'']]],
  ['datapostprocessorvector_23',['DataPostprocessorVector',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorVector.html',1,'']]],
  ['dataset_24',['DataSet',['http://www.dealii.org/developer/doxygen/deal.II/classHDF5_1_1DataSet.html',1,'HDF5']]],
  ['datasetdescriptor_25',['DataSetDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector_1_1DataSetDescriptor.html',1,'QProjector']]],
  ['datavector_26',['DataVector',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutStack_1_1DataVector.html',1,'DataOutStack']]],
  ['deal_5fii_5fintermediateflags_27',['Deal_II_IntermediateFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1Deal__II__IntermediateFlags.html',1,'DataOutBase']]],
  ['default_28',['Default',['http://www.dealii.org/developer/doxygen/deal.II/structMemorySpace_1_1Default.html',1,'MemorySpace']]],
  ['defaulthierarchy_29',['DefaultHierarchy',['http://www.dealii.org/developer/doxygen/deal.II/structhp_1_1FECollection_1_1DefaultHierarchy.html',1,'hp::FECollection']]],
  ['defaultpolicy_30',['DefaultPolicy',['http://www.dealii.org/developer/doxygen/deal.II/classRepartitioningPolicyTools_1_1DefaultPolicy.html',1,'RepartitioningPolicyTools']]],
  ['deleter_31',['Deleter',['http://www.dealii.org/developer/doxygen/deal.II/classAlignedVector_1_1Deleter.html',1,'AlignedVector']]],
  ['deleteractionbase_32',['DeleterActionBase',['http://www.dealii.org/developer/doxygen/deal.II/classAlignedVector_1_1Deleter_1_1DeleterActionBase.html',1,'AlignedVector::Deleter']]],
  ['derivativeform_33',['DerivativeForm',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20spacedim_20_3e_34',['DerivativeForm&lt; 1, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20spacedim_2c_20number_20_3e_35',['DerivativeForm&lt; 1, dim, spacedim, Number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20spacedim_2c_20dim_2c_20number_20_3e_36',['DerivativeForm&lt; 1, spacedim, dim, Number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeselector_37',['DerivativeSelector',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_201_2c_20dim_20_3e_38',['DerivativeSelector&lt; 1, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_011_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_202_2c_20dim_20_3e_39',['DerivativeSelector&lt; 2, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_012_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_203_2c_20dim_20_3e_40',['DerivativeSelector&lt; 3, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_013_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['description_41',['Description',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulationDescription_1_1Description.html',1,'TriangulationDescription']]],
  ['detector_42',['detector',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector.html',1,'internal::SupportsOperation']]],
  ['detector_3c_20default_2c_20void_2c_20op_2c_20args_2e_2e_2e_20_3e_43',['detector&lt; Default, void, Op, Args... &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector.html',1,'internal::SupportsOperation']]],
  ['detector_3c_20default_2c_20void_5ft_3c_20op_3c_20args_2e_2e_2e_20_3e_20_3e_2c_20op_2c_20args_2e_2e_2e_20_3e_44',['detector&lt; Default, void_t&lt; Op&lt; Args... &gt; &gt;, Op, Args... &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_0f78ab3014b3a6806d036c3d96444b509.html',1,'internal::SupportsOperation']]],
  ['deviceblockvector_45',['DeviceBlockVector',['http://www.dealii.org/developer/doxygen/deal.II/classPortable_1_1DeviceBlockVector.html',1,'Portable']]],
  ['dgp_5fdofs_5fper_5fcomponent_46',['DGP_dofs_per_component',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component.html',1,'internal::MatrixFreeFunctions']]],
  ['dgp_5fdofs_5fper_5fcomponent_3c_201_2c_20degree_20_3e_47',['DGP_dofs_per_component&lt; 1, degree &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component_3_011_00_01degree_01_4.html',1,'internal::MatrixFreeFunctions']]],
  ['diagonalmatrix_48',['DiagonalMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classDiagonalMatrix.html',1,'']]],
  ['dictionaryoptimizer_49',['DictionaryOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1DictionaryOptimizer.html',1,'Differentiation::SD::internal']]],
  ['dictionarysubstitutionvisitor_50',['DictionarySubstitutionVisitor',['http://www.dealii.org/developer/doxygen/deal.II/classDifferentiation_1_1SD_1_1internal_1_1DictionarySubstitutionVisitor.html',1,'Differentiation::SD::internal']]],
  ['dimension_3c_3a_3apoint_3c_20dim_2c_20number_20_3e_20_3e_51',['dimension&lt;::Point&lt; dim, Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structboost_1_1geometry_1_1traits_1_1dimension_3_1_1Point_3_01dim_00_01Number_01_4_01_4.html',1,'boost::geometry::traits']]],
  ['directionalprojectionmanifold_52',['DirectionalProjectionManifold',['http://www.dealii.org/developer/doxygen/deal.II/classOpenCASCADE_1_1DirectionalProjectionManifold.html',1,'OpenCASCADE']]],
  ['directoryname_53',['DirectoryName',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1DirectoryName.html',1,'Patterns']]],
  ['discretefacequadraturegenerator_54',['DiscreteFaceQuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteFaceQuadratureGenerator.html',1,'NonMatching']]],
  ['discretefacequadraturegenerator_3c_20dim_20_3e_55',['DiscreteFaceQuadratureGenerator&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteFaceQuadratureGenerator.html',1,'NonMatching']]],
  ['discretelevelsetdescription_56',['DiscreteLevelSetDescription',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1DiscreteLevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['discretequadraturegenerator_57',['DiscreteQuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteQuadratureGenerator.html',1,'NonMatching']]],
  ['discretequadraturegenerator_3c_20dim_20_3e_58',['DiscreteQuadratureGenerator&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteQuadratureGenerator.html',1,'NonMatching']]],
  ['discretetime_59',['DiscreteTime',['http://www.dealii.org/developer/doxygen/deal.II/classDiscreteTime.html',1,'']]],
  ['distortedcelllist_60',['DistortedCellList',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulation_1_1DistortedCellList.html',1,'Triangulation']]],
  ['distributedcomputeintersectionlocationsinternal_61',['DistributedComputeIntersectionLocationsInternal',['http://www.dealii.org/developer/doxygen/deal.II/structGridTools_1_1internal_1_1DistributedComputeIntersectionLocationsInternal.html',1,'GridTools::internal']]],
  ['distributedcomputepointlocationsinternal_62',['DistributedComputePointLocationsInternal',['http://www.dealii.org/developer/doxygen/deal.II/structGridTools_1_1internal_1_1DistributedComputePointLocationsInternal.html',1,'GridTools::internal']]],
  ['distributedtree_63',['DistributedTree',['http://www.dealii.org/developer/doxygen/deal.II/classArborXWrappers_1_1DistributedTree.html',1,'ArborXWrappers']]],
  ['distributedtriangulationbase_64',['DistributedTriangulationBase',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['distributedtriangulationbase_3c_201_2c_20spacedim_20_3e_65',['DistributedTriangulationBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['dofaccessor_66',['DoFAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_200_2c_201_2c_20spacedim_2c_20lda_20_3e_67',['DoFAccessor&lt; 0, 1, spacedim, lda &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_200_2c_201_2c_20spacedim_2c_20level_5fdof_5faccess_20_3e_68',['DoFAccessor&lt; 0, 1, spacedim, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor_3_010_00_011_00_01spacedim_00_01level__dof__access_01_4.html',1,'']]],
  ['dofaccessor_3c_201_2c_202_2c_20spacedim_2c_20lda_20_3e_69',['DoFAccessor&lt; 1, 2, spacedim, lda &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_202_2c_203_2c_20spacedim_2c_20lda_20_3e_70',['DoFAccessor&lt; 2, 3, spacedim, lda &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_20dimension_5f_2c_20dimension_5f_2c_20space_5fdimension_5f_2c_20level_5fdof_5faccess_20_3e_71',['DoFAccessor&lt; dimension_, dimension_, space_dimension_, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofcellaccessor_72',['DoFCellAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['dofcellaccessor_3c_201_2c_20spacedim_2c_20lda_20_3e_73',['DoFCellAccessor&lt; 1, spacedim, lda &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['dofcellaccessor_3c_202_2c_20spacedim_2c_20lda_20_3e_74',['DoFCellAccessor&lt; 2, spacedim, lda &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['dofcellaccessor_3c_203_2c_20spacedim_2c_20lda_20_3e_75',['DoFCellAccessor&lt; 3, spacedim, lda &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['doffaces_76',['DoFFaces',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_201_20_3e_77',['DoFFaces&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_011_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_202_20_3e_78',['DoFFaces&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_012_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_203_20_3e_79',['DoFFaces&lt; 3 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_013_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['dofhandler_80',['DoFHandler',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_201_2c_20spacedim_20_3e_81',['DoFHandler&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_20_3e_82',['DoFHandler&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_2c_20dim_20_3e_83',['DoFHandler&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_2c_20spacedim_20_3e_84',['DoFHandler&lt; dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dimension_2c_20space_5fdimension_20_3e_85',['DoFHandler&lt; dimension, space_dimension &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dimension_5f_2c_20space_5fdimension_5f_20_3e_86',['DoFHandler&lt; dimension_, space_dimension_ &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20patch_5fdim_2c_20spacedim_20_3e_87',['DoFHandler&lt; patch_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20reduced_5fdim_2c_20spacedim_20_3e_88',['DoFHandler&lt; reduced_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofindexprocessor_89',['DoFIndexProcessor',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1DoFAccessorImplementation_1_1Implementation_1_1DoFIndexProcessor.html',1,'internal::DoFAccessorImplementation::Implementation']]],
  ['dofinfo_90',['DoFInfo',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DoFInfo.html',1,'internal::MatrixFreeFunctions::DoFInfo'],['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfo.html',1,'MeshWorker::DoFInfo&lt; int dim, int spacedim, typename number &gt;']]],
  ['dofinfobox_91',['DoFInfoBox',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfoBox.html',1,'MeshWorker']]],
  ['dofinvalidaccessor_92',['DoFInvalidAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFInvalidAccessor.html',1,'']]],
  ['doflevel_93',['DoFLevel',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFLevel.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_94',['DoFObjects',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_201_20_3e_95',['DoFObjects&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_202_20_3e_96',['DoFObjects&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_20dim_20_3e_97',['DoFObjects&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofoutputoperator_98',['DoFOutputOperator',['http://www.dealii.org/developer/doxygen/deal.II/classAlgorithms_1_1DoFOutputOperator.html',1,'Algorithms']]],
  ['dofpair_99',['DoFPair',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MGTransfer_1_1DoFPair.html',1,'internal::MGTransfer']]],
  ['dofprintsolverstep_100',['DoFPrintSolverStep',['http://www.dealii.org/developer/doxygen/deal.II/classDoFPrintSolverStep.html',1,'']]],
  ['dot_101',['Dot',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1VectorOperations_1_1Dot.html',1,'internal::VectorOperations']]],
  ['double_102',['Double',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1Double.html',1,'Patterns']]],
  ['double_5fcontraction_5fresult_103',['double_contraction_result',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result.html',1,'internal::SymmetricTensorAccessors']]],
  ['double_5fcontraction_5fresult_3c_202_2c_202_2c_20dim_2c_20number_2c_20othernumber_20_3e_104',['double_contraction_result&lt; 2, 2, dim, Number, OtherNumber &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result_3_012_00_012_00_01dim_bde24087db8a52ec06f500b41dd95304.html',1,'internal::SymmetricTensorAccessors']]],
  ['duplicatedcommunicator_105',['DuplicatedCommunicator',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1DuplicatedCommunicator.html',1,'Utilities::MPI']]],
  ['dx_106',['DX',['http://www.dealii.org/developer/doxygen/deal.II/structGridOutFlags_1_1DX.html',1,'GridOutFlags']]],
  ['dxflags_107',['DXFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DXFlags.html',1,'DataOutBase']]],
  ['dynamicsparsitypattern_108',['DynamicSparsityPattern',['http://www.dealii.org/developer/doxygen/deal.II/classDynamicSparsityPattern.html',1,'']]]
];
