var searchData=
[
  ['maxwell_20eigenvalue_20problem_20code_20gallery_20program_0',['The &apos;Goal-Oriented hp-Adaptivity for the Maxwell Eigenvalue Problem&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Maxwell_Eigenvalue-hp-Refinement.html',1,'']]],
  ['mcmc_20for_20the_20laplace_20equation_20code_20gallery_20program_1',['The &apos;MCMC for the Laplace equation&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MCMC_Laplace.html',1,'']]],
  ['mesh_20adaptivity_20in_20elastoplasticity_20problems_20code_20gallery_20program_2',['The &apos;Goal-oriented mesh adaptivity in elastoplasticity problems&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_goal_oriented_elastoplasticity.html',1,'']]],
  ['mesh_20refinement_20code_20gallery_20program_3',['The &apos;Information density-based mesh refinement&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_information_based_mesh_refinement.html',1,'']]],
  ['method_20code_20gallery_20program_4',['The &apos;Distributed LDG Method&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Distributed_LDG_Method.html',1,'']]],
  ['methods_20code_20gallery_20program_5',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['mfmfe_20methods_20code_20gallery_20program_6',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['mixed_20finite_20element_20mfmfe_20methods_20code_20gallery_20program_7',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['model_20code_20gallery_20program_8',['The &apos;Linear Elastic Active Skeletal Muscle Model&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Linear_Elastic_Active_Skeletal_Muscle_Model.html',1,'']]],
  ['moving_20laser_20heating_20code_20gallery_20program_9',['The &apos;Distributed moving laser heating&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Distributed_Moving_Laser_Heating.html',1,'']]],
  ['multipoint_20flux_20mixed_20finite_20element_20mfmfe_20methods_20code_20gallery_20program_10',['The &apos;Higher Order Multipoint Flux Mixed Finite Element (MFMFE) methods&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_MultipointFluxMixedFiniteElementMethods.html',1,'']]],
  ['muscle_20model_20code_20gallery_20program_11',['The &apos;Linear Elastic Active Skeletal Muscle Model&apos; code gallery program',['http://www.dealii.org/developer/doxygen/deal.II/code_gallery_Linear_Elastic_Active_Skeletal_Muscle_Model.html',1,'']]]
];
