# CMake generated Testfile for 
# Source directory: /calculate/RLM/tests
# Build directory: /calculate/RLM/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests/template.debug "/usr/bin/cmake" "-DTRGT=tests.template.debug.test" "-DTEST=tests/template.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/calculate/RLM" "-P" "/opt/dealii-9.5.0_hdf5/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.5.0-26o4yaol7efkmvn46onattkytp7bluzi/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/template.debug PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/calculate/RLM/tests/template.debug" _BACKTRACE_TRIPLES "/opt/dealii-9.5.0_hdf5/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.5.0-26o4yaol7efkmvn46onattkytp7bluzi/share/deal.II/macros/macro_deal_ii_add_test.cmake;577;add_test;/opt/dealii-9.5.0_hdf5/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.5.0-26o4yaol7efkmvn46onattkytp7bluzi/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;343;deal_ii_add_test;/calculate/RLM/tests/CMakeLists.txt;2;DEAL_II_PICKUP_TESTS;/calculate/RLM/tests/CMakeLists.txt;0;")
add_test(tests/test_fourier_01.debug "/usr/bin/cmake" "-DTRGT=tests.test_fourier_01.debug.test" "-DTEST=tests/test_fourier_01.debug" "-DEXPECT=PASSED" "-DBINARY_DIR=/calculate/RLM" "-P" "/opt/dealii-9.5.0_hdf5/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.5.0-26o4yaol7efkmvn46onattkytp7bluzi/share/deal.II/scripts/run_test.cmake")
set_tests_properties(tests/test_fourier_01.debug PROPERTIES  LABEL "tests" PROCESSORS "1" TIMEOUT "600" WORKING_DIRECTORY "/calculate/RLM/tests/test_fourier_01.debug" _BACKTRACE_TRIPLES "/opt/dealii-9.5.0_hdf5/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.5.0-26o4yaol7efkmvn46onattkytp7bluzi/share/deal.II/macros/macro_deal_ii_add_test.cmake;577;add_test;/opt/dealii-9.5.0_hdf5/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/dealii-9.5.0-26o4yaol7efkmvn46onattkytp7bluzi/share/deal.II/macros/macro_deal_ii_pickup_tests.cmake;343;deal_ii_add_test;/calculate/RLM/tests/CMakeLists.txt;2;DEAL_II_PICKUP_TESTS;/calculate/RLM/tests/CMakeLists.txt;0;")
