FROM dealii/dealii:master-focal

LABEL maintainer="luca.heltai@gmail.com"

USER $USER
WORKDIR $HOME
RUN mkdir -p $HOME/.vscode-server/ &&\
    mkdir -p $HOME/.vscode-server-insiders/ &&\
    mkdir -p $HOME/.ssh/
